# Generated by Django 5.1.1 on 2024-09-13 23:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEnergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Tipo de energia', max_length=100, unique=True, verbose_name='Tipo')),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custoAnterior', models.DecimalField(decimal_places=2, help_text='Preço anterior', max_digits=10, verbose_name='CustoAnterior')),
                ('custoAtual', models.DecimalField(decimal_places=2, help_text='Preço atual', max_digits=10, verbose_name='CustoAtual')),
                ('duracao', models.DecimalField(decimal_places=2, help_text='Jornada', max_digits=10, verbose_name='Duracao')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('energiaAnterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_energia_anterior', to='site_cityhub.typeenergy')),
                ('energiaAtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_energia_atual', to='site_cityhub.typeenergy')),
            ],
        ),
    ]
