volumes:
  db_data: {}

services:
  sitecityhub:
    build: .
    image: barbaradiogo/sitecityhub
    ports: 
      - 8200:8200
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8200"
    volumes:
      - .:/app
    depends_on:
      - banco
  banco:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: senha 
      POSTGRES_DB: cityhubbd
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
# Quando eu uso um arquivo compose, preciso comentar alguns comandos no meus Dockerfile, porque serão executados aqui.